stages:
   - build
   - test
   - sign
   - deploy

# Creates installer exe  and macos executable files

build:macos:
  image: node:12.18.4
  stage: build
  tags: 
    - runner
  script: 
  - cd app
  - make build:osx
  artifacts:
    paths:
      - binaries/

build:windows:
  image: node:12.18.4
  stage: build
  tags: 
    - runner  
  script:
   - cd app
   - make build:macox
  artifacts:
    paths:
      - binaries/


test:
  image: node:12.18.4
  stage: test
  script:
     - npm test // script for test 

# Sign and Notorize the executables
# RUns on the runner with tag 'windows'
sign_windows_exe:
   image: FROM mcr.microsoft.com/windows/servercore:ltsc2019
   tags: 
    - windows
   stage: sign
   script: 
   # Run powershell script on windows runner to sign the .exe file
   - powershell -File "\signing\sign-exe.ps1" binaries/MyApp.exe

sign_macos:
    image: alpinelinux/docker-alpine
    tags:
      - runner
    stage: sign
    script:
      - sh signing/sign-macos.sh MyAppMacOS

notarize_macos:
    image: alpinelinux/docker-alpine
    tags:
      - runner
    stage: sign
    script:
      - sh signing/notarize-macos.sh MyAppMacOS


deploy:
tags: 
    - runner,windows
  stage: deploy
  script: make deploy
  # deploy exe to intune
  #deploy macos to AppStore