image:
    name: docker:19.03.12
    entrypoint: [""]

services:
    - docker:19.03.12-dind

variables:
    ECR_URL: "${ecr_url}" 
    REGION: "${region}" 
    DOCKER_HOST: "${docker_host}" 
    TASK_DEFN: "${task_defn}" 
    CLUSTER_NAME: "${cluster_name}" 
    SVC_NAME: "${svc_name}" 

stages:
   - build
   - package
   - sign_windows_exe
   - sign_macos
   - notarize_macos
   - deploy

# Creates installer exe  and macos executable files

build:macos:
  image: node:12.18.4
  stage: build
  tags: 
    - runner
  script: 
  - cd app
  - make build:osx
  artifacts:
    paths:
      - binaries/

build:windows:
  image: node:12.18.4
  stage: build
  tags: 
    - runner  
  script:
   - cd app
   - make build:macox
  artifacts:
    paths:
      - binaries/

deploy:
tags: 
    - runner
  stage: deploy
  script: make deploy



# Sign and Notorize the executables
# RUns on the runner with tag 'windows'
sign_windows_exe:
   image: FROM mcr.microsoft.com/windows/servercore:ltsc2019
   tags: 
    - windows
   stage: sign_windows_exe
   script: 
   # Run powershell script on windows runner to sign the .exe file
   - powershell -File "\signing\sign-exe.ps1" binaries/MyApp.exe

sign_macos:
    image: alpinelinux/docker-alpine
    tags:
      - runner
    stage: sign_macos
    script:
      - sh signing/sign-macos.sh MyAppMacOS

notarize_macos:
    image: alpinelinux/docker-alpine
    tags:
      - runner
    stage: notarize_macos
    script:
      - sh signing/notarize-macos.sh MyAppMacOS